# Generated by Django 5.2.3 on 2025-07-04 03:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '__first__'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='companion_id')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('identity_document_type', models.CharField(choices=[('Passport', 'Passport'), ('National Identity Document', 'National_Id_Document'), ('Identity Card', 'Id_Card'), ('Residence Permit', 'Residence_Permit'), ("Driver's License", 'Driver_License'), ('Birth Certificate', 'Birth_Certificate'), ('Foreigner Identification Number', 'Foreigner_Identification_Number'), ('Social Security Number', 'Social_Security_Number'), ('Social Insurance Number', 'Social_Insurance_Number'), ('Tax Identification Number', 'Tax_Identification_Number'), ('Voter Identification Card', 'Voter_Identification_Card'), ('Passport Card', 'Passport_Card'), ('Military ID', 'Military_Id'), ('Student ID', 'Student_Id'), ('Health Insurance Card', 'Health_Insurance_Card'), ('Visa', 'Visa'), ('Work Permit', 'Work_Permit'), ('Travel Document', 'Travel_Document'), ('Police Identification Card', 'Police_Id'), ('Maritime Document', 'Maritime_Document')], max_length=64)),
                ('identity_document', models.CharField(max_length=255)),
                ('born_date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=8)),
                ('observations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ORDERED', 'Ordered'), ('EXPIRED', 'Expired')], default='OPEN', max_length=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('items_cnt', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='clients.clients')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_id', models.PositiveIntegerField()),
                ('product_metadata_id', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='order_id')),
                ('date', models.DateTimeField()),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('UPCOMING', 'Upcoming'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=32)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total de la orden', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='order_detail_id')),
                ('availability_id', models.PositiveIntegerField(help_text='ID de la disponibilidad específica (ActivityAvailability, RoomAvailability, etc.)')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio unitario del producto', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal del detalle', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_applied', models.DecimalField(decimal_places=2, help_text='Descuento aplicado', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.packages')),
                ('product_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsmetadata')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='notification_id')),
                ('email_destination', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
                ('notification_type', models.CharField(choices=[('BOOKING_PENDING', 'Booking Pending'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('TRIP_UPCOMING_REMINDER', 'Upcoming Trip Reminder'), ('TRIP_STARTED', 'Trip Started'), ('TRIP_COMPLETED', 'Trip Completed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('REFUND_ISSUED', 'Refund Issued')], max_length=32)),
                ('shipping_state', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Upcoming', 'Upcoming'), ('In Progress', 'In_Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], max_length=32)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='sale_id')),
                ('transaction_number', models.IntegerField()),
                ('sale_date', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, help_text='Total de la venta', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_status', models.CharField(choices=[('DUE', 'Due'), ('PAID_CASH', 'Paid (Cash)'), ('PAID_CHEQUE', 'Paid (Cheque)'), ('PAID_ONLINE', 'Paid (Online)'), ('CANCELLED', 'Cancelled')], default='DUE', max_length=20)),
                ('sale_type', models.CharField(choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale'), ('ONLINE', 'Online'), ('IN_STORE', 'In‑Store'), ('BACKORDER', 'Backorder')], default='RETAIL', max_length=20)),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('ONLINE', 'Online Payment'), ('WIRE_TRANSFER', 'Wire Transfer')], default='ONLINE', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='bill_id')),
                ('bill_number', models.PositiveIntegerField()),
                ('emission_date', models.DateTimeField()),
                ('items_details', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, help_text='Total de la factura', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('UNPAID', 'Unpaid'), ('SCHEDULED', 'Scheduled'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('REFUNDED', 'Refunded'), ('CANCELED', 'Canceled'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('bill_type', models.CharField(choices=[('STANDARD', 'Standard'), ('PROFORMA', 'Pro Forma'), ('INTERIM', 'Interim'), ('FINAL', 'Final'), ('RECURRING', 'Recurring'), ('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('TIMESHEET', 'Timesheet'), ('COMMERCIAL', 'Commercial'), ('EXPENSE', 'Expense'), ('COMPOSITE', 'Composite'), ('PAST_DUE', 'Past Due')], default='STANDARD', max_length=15)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sales')),
            ],
        ),
        migrations.CreateModel(
            name='StoreIdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('method', models.CharField(max_length=6)),
                ('path', models.CharField(max_length=256)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'In progress'), (1, 'Completed'), (2, 'Failed')], default=0)),
                ('response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='voucher_id')),
                ('emission_date', models.DateTimeField()),
                ('voucher_code', models.CharField(max_length=128)),
                ('passenger_type', models.CharField(choices=[('CLIENT', 'Client'), ('COMPANY', 'Companion')], default='CLIENT', max_length=32)),
                ('state', models.CharField(choices=[('AVAILABLE', 'Available'), ('ISSUED', 'Issued'), ('REDEEMED', 'Redeemed'), ('EXPIRED', 'Expired'), ('RETRACTED', 'Retracted')], default='AVAILABLE', max_length=32)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.companions')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sales')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='voucher_detail_id')),
                ('service_name', models.CharField(max_length=32)),
                ('product_type', models.CharField(choices=[('ACTIVITY', 'Activity'), ('FLIGHT', 'Flight'), ('LODGMENT', 'Lodgments'), ('TRANSPORTATION', 'Transportation')], max_length=32)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.CharField(max_length=32)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.packages')),
                ('product_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsmetadata')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.vouchers')),
            ],
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['client', 'status'], name='store_cart_client__e052eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'availability_id')},
        ),
        migrations.AddIndex(
            model_name='storeidempotencyrecord',
            index=models.Index(fields=['created_at'], name='store_store_created_87a194_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storeidempotencyrecord',
            unique_together={('key', 'user', 'method', 'path')},
        ),
    ]
