# Generated by Django 5.2.3 on 2025-06-29 04:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('products', '0002_activities_deleted_at_activities_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='companion_id')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('identity_document_type', models.CharField(choices=[('Passport', 'Passport'), ('National Identity Document', 'National_Id_Document'), ('Identity Card', 'Id_Card'), ('Residence Permit', 'Residence_Permit'), ("Driver's License", 'Driver_License'), ('Birth Certificate', 'Birth_Certificate'), ('Foreigner Identification Number', 'Foreigner_Identification_Number'), ('Social Security Number', 'Social_Security_Number'), ('Social Insurance Number', 'Social_Insurance_Number'), ('Tax Identification Number', 'Tax_Identification_Number'), ('Voter Identification Card', 'Voter_Identification_Card'), ('Passport Card', 'Passport_Card'), ('Military ID', 'Military_Id'), ('Student ID', 'Student_Id'), ('Health Insurance Card', 'Health_Insurance_Card'), ('Visa', 'Visa'), ('Work Permit', 'Work_Permit'), ('Travel Document', 'Travel_Document'), ('Police Identification Card', 'Police_Id'), ('Maritime Document', 'Maritime_Document')])),
                ('identity_document', models.CharField(max_length=255)),
                ('born_date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F')])),
                ('observations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='order_id')),
                ('date', models.DateTimeField()),
                ('state', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Upcoming', 'Upcoming'), ('In Progress', 'In_Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')])),
                ('total', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.addresses')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='order_detail_id')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_applied', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.packages')),
                ('product_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsmetadata')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='notification_id')),
                ('email_destination', models.EmailField(max_length=254)),
                ('subject', models.CharField()),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
                ('notification_type', models.CharField(choices=[('BOOKING_PENDING', 'Booking Pending'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('TRIP_UPCOMING_REMINDER', 'Upcoming Trip Reminder'), ('TRIP_STARTED', 'Trip Started'), ('TRIP_COMPLETED', 'Trip Completed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('REFUND_ISSUED', 'Refund Issued')])),
                ('shipping_state', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Upcoming', 'Upcoming'), ('In Progress', 'In_Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='sale_id')),
                ('transaction_number', models.IntegerField()),
                ('sale_date', models.DateTimeField()),
                ('total', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_status', models.CharField(choices=[('DUE', 'Due'), ('PAID_CASH', 'Paid (Cash)'), ('PAID_CHEQUE', 'Paid (Cheque)'), ('PAID_ONLINE', 'Paid (Online)'), ('CANCELLED', 'Cancelled')], default='DUE', max_length=20)),
                ('sale_type', models.CharField(choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale'), ('ONLINE', 'Online'), ('IN_STORE', 'In‑Store'), ('BACKORDER', 'Backorder')], default='RETAIL', max_length=20)),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('ONLINE', 'Online Payment'), ('WIRE_TRANSFER', 'Wire Transfer')], default='ONLINE', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='bill_id')),
                ('bill_number', models.PositiveIntegerField()),
                ('emission_date', models.DateTimeField()),
                ('items_details', models.TextField()),
                ('total', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('UNPAID', 'Unpaid'), ('SCHEDULED', 'Scheduled'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('REFUNDED', 'Refunded'), ('CANCELED', 'Canceled'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('bill_type', models.CharField(choices=[('STANDARD', 'Standard'), ('PROFORMA', 'Pro Forma'), ('INTERIM', 'Interim'), ('FINAL', 'Final'), ('RECURRING', 'Recurring'), ('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('TIMESHEET', 'Timesheet'), ('COMMERCIAL', 'Commercial'), ('EXPENSE', 'Expense'), ('COMPOSITE', 'Composite'), ('PAST_DUE', 'Past Due')], default='STANDARD', max_length=15)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sales')),
            ],
        ),
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='voucher_id')),
                ('emission_date', models.DateTimeField()),
                ('voucher_code', models.CharField(max_length=128)),
                ('passenger_type', models.CharField(choices=[('CLIENT', 'Client'), ('COMPANY', 'Companion')], default='CLIENT')),
                ('state', models.CharField(choices=[('AVAILABLE', 'Available'), ('ISSUED', 'Issued'), ('REDEEMED', 'Redeemed'), ('EXPIRED', 'Expired'), ('RETRACTED', 'Retracted')], default='AVAILABLE')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.companions')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sales')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='voucher_detail_id')),
                ('service_name', models.CharField(max_length=32)),
                ('product_type', models.CharField(choices=[('AVAILABLE', 'Available'), ('ISSUED', 'Issued'), ('REDEEMED', 'Redeemed'), ('EXPIRED', 'Expired'), ('RETRACTED', 'Retracted')])),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.CharField(max_length=32)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.packages')),
                ('product_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsmetadata')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.vouchers')),
            ],
        ),
    ]
