# Generated by Django 5.2.3 on 2025-07-07 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.productsmetadata'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Paquete asociado (opcional para productos individuales)', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.packages'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='product_metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsmetadata'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orders'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orders'),
        ),
        migrations.AddField(
            model_name='sales',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orders'),
        ),
        migrations.AddField(
            model_name='bills',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sales'),
        ),
        migrations.AddField(
            model_name='storeidempotencyrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucherdetails',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.packages'),
        ),
        migrations.AddField(
            model_name='voucherdetails',
            name='product_metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsmetadata'),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='passenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.companions'),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sales'),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucherdetails',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.vouchers'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'status'], name='store_cart_user_id_6ecadc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'availability_id')},
        ),
        migrations.AddIndex(
            model_name='storeidempotencyrecord',
            index=models.Index(fields=['created_at'], name='store_store_created_87a194_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storeidempotencyrecord',
            unique_together={('key', 'user', 'method', 'path')},
        ),
    ]
