# Generated by Django 5.2.3 on 2025-07-01 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Total de la factura', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, help_text='Descuento aplicado', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='Subtotal del detalle', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Precio unitario del producto', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Total de la orden', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Total de la venta', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
