# Generated by Django 5.2.3 on 2025-07-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_storeidempotencyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='availability_id',
            field=models.PositiveIntegerField(default=1, help_text='ID de la disponibilidad específica (ActivityAvailability, RoomAvailability, etc.)'),
            preserve_default=False,
        ),
    ]
