# Generated by Django 5.2.3 on 2025-06-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='address_id')),
                ('street', models.CharField(max_length=64)),
                ('street_number', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('zip_code', models.CharField(max_length=64)),
                ('address_type', models.CharField(choices=[])),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='client_id')),
                ('identity_document_type', models.CharField(choices=[('Passport', 'Passport'), ('National Identity Document', 'National_Id_Document'), ('Identity Card', 'Id_Card'), ('Residence Permit', 'Residence_Permit'), ("Driver's License", 'Driver_License'), ('Birth Certificate', 'Birth_Certificate'), ('Foreigner Identification Number', 'Foreigner_Identification_Number'), ('Social Security Number', 'Social_Security_Number'), ('Social Insurance Number', 'Social_Insurance_Number'), ('Tax Identification Number', 'Tax_Identification_Number'), ('Voter Identification Card', 'Voter_Identification_Card'), ('Passport Card', 'Passport_Card'), ('Military ID', 'Military_Id'), ('Student ID', 'Student_Id'), ('Health Insurance Card', 'Health_Insurance_Card'), ('Visa', 'Visa'), ('Work Permit', 'Work_Permit'), ('Travel Document', 'Travel_Document'), ('Police Identification Card', 'Police_Id'), ('Maritime Document', 'Maritime_Document')])),
                ('identity_document', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=32)),
            ],
        ),
    ]
