# Generated by Django 5.2.3 on 2025-06-22 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='employee_id')),
                ('employee_file', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Audits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='audit_id')),
                ('action', models.CharField(max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
