# Generated by Django 4.2.7 on 2024-01-15 10:00:00

from django.db import migrations, models
import django.db.models.deletion
import django.contrib.contenttypes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0002_add_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='employee_id')),
                ('employee_file', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='user_id')),
            ],
        ),
        migrations.CreateModel(
            name='Audits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='audit_id')),
                ('action', models.CharField(max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees', verbose_name='employee_id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddIndex(
            model_name='audits',
            index=models.Index(fields=['content_type_id', 'object_id'], name='employees_a_content_8b8b8b_idx'),
        ),
    ] 