# Generated by Django 5.2.3 on 2025-06-27 06:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='package_id')),
                ('name', models.CharField(max_length=64, verbose_name='package_name')),
                ('description', models.TextField()),
                ('final_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='supplier_id')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('organization_name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('street', models.CharField(max_length=32)),
                ('street_number', models.BigIntegerField(help_text='House/street number (puede ser negativo hasta -2 y positivo hasta 200 000)', validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(200000)])),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=16)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='flight_id')),
                ('airline', models.CharField(max_length=32)),
                ('flight_number', models.CharField(max_length=16)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('duration_hours', models.IntegerField(help_text='duration (puede ser positivo y menor o igual a 192)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(192)])),
                ('class_flight', models.CharField(choices=[('Basic Economy', 'Basic_Economy'), ('Economy', 'Economy'), ('Premium Economy', 'Premium_Economy'), ('Business Class', 'Business'), ('First Class', 'First')])),
                ('available_seats', models.IntegerField(help_text='Cantidad de asientos disponibles en este vuelo', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights_arriving', to='products.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights_departing', to='products.location')),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='activity_id')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_hours', models.IntegerField(help_text='duration (tiene que ser positivo y menor o igual a 24)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('include_guide', models.BooleanField()),
                ('maximum_spaces', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('difficulty_level', models.CharField(choices=[('Very Easy', 'Very_Easy'), ('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Very Hard', 'Very_Hard'), ('Extreme', 'Extreme')])),
                ('language', models.CharField()),
                ('available_slots', models.IntegerField(help_text='Cantidad de lugares disponibles para esta actividad', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.location')),
            ],
        ),
        migrations.CreateModel(
            name='Lodgments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='lod_id')),
                ('name', models.CharField(max_length=64, verbose_name='lod_name')),
                ('date_checkin', models.DateField()),
                ('date_checkout', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.location')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsMetadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='product_metadata_id')),
                ('object_id', models.PositiveIntegerField()),
                ('unit_price', models.FloatField(help_text='Precio base por unidad o persona', validators=[django.core.validators.MinValueValidator(0)])),
                ('product_type', models.CharField(choices=[('actividad', 'Actividad'), ('vuelo', 'Vuelo'), ('alojamiento', 'Alojamiento'), ('transporte', 'Transporte')], help_text='Tipo de product: actividad, vuelo, alojamiento, transporte', max_length=32)),
                ('content_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.suppliers', verbose_name='supplier_id')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentPackages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='component_package_id')),
                ('order', models.IntegerField()),
                ('quantity', models.IntegerField(null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.packages', verbose_name='package_id')),
                ('product_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsmetadata', verbose_name='product_metadata_id')),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='promotion_id')),
                ('name', models.CharField(max_length=64)),
                ('discount', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.packages', verbose_name='package_id')),
                ('product_metadata', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsmetadata', verbose_name='product_metadata_id')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='review_id')),
                ('punctuation', models.FloatField()),
                ('comment', models.TextField()),
                ('date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients', verbose_name='client_id')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.packages', verbose_name='package_id')),
                ('product_metadata', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsmetadata', verbose_name='product_metadata_id')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.IntegerField(help_text='Cantidad máxima de personas por habitación', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('price_per_night', models.FloatField(help_text='Precio base por noche de esta habitación', validators=[django.core.validators.MinValueValidator(0)])),
                ('available_quantity', models.IntegerField(help_text='Cantidad disponible para reservar', validators=[django.core.validators.MinValueValidator(0)])),
                ('lodgment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='products.lodgments')),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='transportation_id')),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('description', models.TextField()),
                ('capacity', models.IntegerField(help_text='Cantidad de lugares disponibles en el transporte', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_arrivals', to='products.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_departures', to='products.location')),
            ],
        ),
    ]
