# Generated by Django 5.2.3 on 2025-07-07 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id'),
        ),
        migrations.AddField(
            model_name='room',
            name='lodgment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='products.lodgments'),
        ),
        migrations.AddField(
            model_name='roomavailability',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='products.room'),
        ),
        migrations.AddIndex(
            model_name='stockauditlog',
            index=models.Index(fields=['operation_type', 'created_at'], name='stock_audit_operati_0e059d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockauditlog',
            index=models.Index(fields=['product_type', 'product_id'], name='stock_audit_product_53872e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockauditlog',
            index=models.Index(fields=['user_id', 'created_at'], name='stock_audit_user_id_fa3702_idx'),
        ),
        migrations.AddIndex(
            model_name='stockauditlog',
            index=models.Index(fields=['session_id'], name='stock_audit_session_ad6417_idx'),
        ),
        migrations.AddIndex(
            model_name='stockauditlog',
            index=models.Index(fields=['success'], name='stock_audit_success_69c1c8_idx'),
        ),
        migrations.AddField(
            model_name='stockchangehistory',
            name='audit_log',
            field=models.ForeignKey(help_text='Referencia al log de auditoría principal', on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='products.stockauditlog'),
        ),
        migrations.AddIndex(
            model_name='stockmetrics',
            index=models.Index(fields=['product_type', 'product_id', 'date'], name='stock_metri_product_030b84_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmetrics',
            index=models.Index(fields=['date', 'utilization_rate'], name='stock_metri_date_08c77f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockmetrics',
            unique_together={('product_type', 'product_id', 'date')},
        ),
        migrations.AddField(
            model_name='productsmetadata',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.suppliers'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_arrivals', to='products.location'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_departures', to='products.location'),
        ),
        migrations.AddField(
            model_name='transportationavailability',
            name='transportation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='products.transportation'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['country', 'state', 'city', 'type'], name='products_lo_country_c84dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='products_lo_name_2b03d9_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['code'], name='products_lo_code_e853b5_idx'),
        ),
        migrations.AddIndex(
            model_name='lodgments',
            index=models.Index(fields=['type', 'is_active'], name='lodgments_type_4fa21b_idx'),
        ),
        migrations.AddIndex(
            model_name='lodgments',
            index=models.Index(fields=['location', 'is_active'], name='lodgments_locatio_5aa30d_idx'),
        ),
        migrations.AddIndex(
            model_name='lodgments',
            index=models.Index(fields=['date_checkin', 'date_checkout'], name='lodgments_date_ch_b6dfeb_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['lodgment', 'room_type'], name='rooms_lodgmen_d773d4_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type', 'is_active'], name='rooms_room_ty_40f0ff_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['capacity'], name='rooms_capacit_c8100e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('lodgment', 'room_type', 'name')},
        ),
        migrations.AddIndex(
            model_name='roomavailability',
            index=models.Index(fields=['room', 'start_date', 'end_date'], name='room_availa_room_id_337d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='roomavailability',
            index=models.Index(fields=['start_date', 'end_date'], name='room_availa_start_d_e63470_idx'),
        ),
        migrations.AddIndex(
            model_name='roomavailability',
            index=models.Index(fields=['is_blocked'], name='room_availa_is_bloc_415f3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomavailability',
            unique_together={('room', 'start_date', 'end_date')},
        ),
        migrations.AddIndex(
            model_name='stockchangehistory',
            index=models.Index(fields=['audit_log', 'field_name'], name='stock_chang_audit_l_3bb627_idx'),
        ),
        migrations.AddIndex(
            model_name='stockchangehistory',
            index=models.Index(fields=['change_type', 'created_at'], name='stock_chang_change__3c99f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transportationavailability',
            unique_together={('transportation', 'departure_date', 'departure_time')},
        ),
    ]
