# Generated by Django 5.2.3 on 2025-06-28 05:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodgments',
            name='space',
        ),
        migrations.AddField(
            model_name='productsmetadata',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productsmetadata',
            name='product_type',
            field=models.CharField(choices=[('ACTIVITY', 'Activity'), ('FLIGHT', 'Flight'), ('LODGMENT', 'Lodgment'), ('TRANSPORTATION', 'Transportation')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsmetadata',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flights',
            name='arrival_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='departure_date',
            field=models.DateTimeField(),
        ),
    ]
