# Generated by Django 5.2.3 on 2025-06-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmetadata',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsmetadata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
