# Generated by Django 5.2.3 on 2025-06-30 01:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_roomavailability_remove_lodgments_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportation',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='departure_date',
        ),
        migrations.AddField(
            model_name='transportation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='type',
            field=models.CharField(choices=[('bus', 'Bus'), ('van', 'Van'), ('car', 'Auto privado'), ('shuttle', 'Shuttle'), ('train', 'Tren'), ('other', 'Otro')], default='bus', max_length=16),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TransportationAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('total_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reserved_seats', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('state', models.CharField(default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='products.transportation')),
            ],
            options={
                'unique_together': {('transportation', 'departure_date', 'departure_time')},
            },
        ),
    ]
