# Generated by Django 5.2.3 on 2025-06-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_activities_deleted_at_activities_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='difficulty_level',
            field=models.CharField(choices=[('Very Easy', 'Very_Easy'), ('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Very Hard', 'Very_Hard'), ('Extreme', 'Extreme')], max_length=16),
        ),
        migrations.AlterField(
            model_name='flights',
            name='class_flight',
            field=models.CharField(choices=[('Basic Economy', 'Basic_Economy'), ('Economy', 'Economy'), ('Premium Economy', 'Premium_Economy'), ('Business Class', 'Business'), ('First Class', 'First')], max_length=16),
        ),
    ]
