# Generated by Django 5.2.3 on 2025-07-07 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentpackages',
            name='availability_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packages/images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_cover', models.BooleanField(default=False, help_text='¿Es la imagen principal del paquete?')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.packages')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_cover', models.BooleanField(default=False, help_text='¿Es la imagen principal del producto?')),
                ('product_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productsmetadata')),
            ],
        ),
    ]
