# Generated by Django 5.2.3 on 2025-06-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_transportation_arrival_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
