# Generated by Django 5.2.3 on 2025-06-30 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_suppliers_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentpackages',
            name='end_date',
            field=models.DateField(blank=True, help_text='Fecha de fin de uso del componente', null=True),
        ),
        migrations.AddField(
            model_name='componentpackages',
            name='start_date',
            field=models.DateField(blank=True, help_text='Fecha de inicio de uso del componente', null=True),
        ),
        migrations.AddField(
            model_name='componentpackages',
            name='title',
            field=models.CharField(blank=True, help_text='Nombre visible del componente en la ficha del paquete', max_length=128),
        ),
        migrations.AddField(
            model_name='packages',
            name='base_price',
            field=models.FloatField(blank=True, help_text='Precio base sin impuestos', null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='cover_image',
            field=models.URLField(blank=True, help_text='Imagen destacada del paquete'),
        ),
        migrations.AddField(
            model_name='packages',
            name='rating_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='packages',
            name='taxes',
            field=models.FloatField(blank=True, help_text='Impuestos o recargos', null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='componentpackages',
            name='order',
            field=models.IntegerField(help_text='Orden de visualización dentro del paquete'),
        ),
        migrations.AlterField(
            model_name='componentpackages',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentpackages', to='products.packages', verbose_name='package_id'),
        ),
        migrations.AlterField(
            model_name='componentpackages',
            name='quantity',
            field=models.IntegerField(help_text='Cantidad de veces que se incluye este producto', null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='final_price',
            field=models.FloatField(help_text='Precio final total del paquete'),
        ),
    ]
