# Generated by Django 5.2.3 on 2025-06-30 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_componentpackages_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='productsmetadata',
            old_name='precio_unitario',
            new_name='unit_price',
        ),
        migrations.AddField(
            model_name='packages',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Categoría del paquete turístico', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.category'),
        ),
    ]
