# Generated by Django 5.2.3 on 2025-06-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='gate',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='terminal',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
