# Generated by Django 5.2.3 on 2025-07-01 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_flights_gate_alter_flights_notes_and_more'),
    ]

    operations = [
    ]
