# Generated by Django 5.2.3 on 2025-07-01 06:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20250630_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='flights',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='departure_time',
        ),
        migrations.AddField(
            model_name='productsmetadata',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productsmetadata',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activities',
            name='available_slots',
            field=models.IntegerField(help_text='Number of available spots for this activity', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='activities',
            name='duration_hours',
            field=models.IntegerField(help_text='duration (must be positive and less than or equal to 24)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='componentpackages',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of component usage', null=True),
        ),
        migrations.AlterField(
            model_name='componentpackages',
            name='order',
            field=models.IntegerField(help_text='Display order within the package'),
        ),
        migrations.AlterField(
            model_name='componentpackages',
            name='quantity',
            field=models.IntegerField(help_text='Number of times this product is included', null=True),
        ),
        migrations.AlterField(
            model_name='componentpackages',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date of component usage', null=True),
        ),
        migrations.AlterField(
            model_name='componentpackages',
            name='title',
            field=models.CharField(blank=True, help_text='Visible name of the component in the package details', max_length=128),
        ),
        migrations.AlterField(
            model_name='packages',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price without taxes', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Tour package category', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.category'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='cover_image',
            field=models.URLField(blank=True, help_text='Featured image of the package'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='final_price',
            field=models.DecimalField(decimal_places=2, help_text='Total final price of the package', max_digits=10),
        ),
        migrations.AlterField(
            model_name='packages',
            name='rating_average',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average rating (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='packages',
            name='taxes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taxes or surcharges', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productsmetadata',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Unit price of the product', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='discount',
            field=models.DecimalField(decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='punctuation',
            field=models.DecimalField(decimal_places=2, help_text='Review rating (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='street_number',
            field=models.BigIntegerField(help_text='House/street number (can be negative up to -2 and positive up to 200,000)', validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(200000)]),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='type',
            field=models.CharField(choices=[('bus', 'Bus'), ('van', 'Van'), ('car', 'Private Car'), ('shuttle', 'Shuttle'), ('train', 'Train'), ('other', 'Other')], default='bus', max_length=16),
        ),
    ]
