# Generated by Django 5.2.3 on 2025-07-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_category_options_remove_flights_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
