# Generated by Django 5.2.3 on 2025-07-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_flights_arrival_time_flights_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
