# Generated by Django 5.2.3 on 2025-07-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_flights_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmetadata',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
