# Generated by Django 5.2.3 on 2025-07-01 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productsmetadata_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='capacity',
            field=models.IntegerField(default=2, help_text='Maximum number of seats for this flight', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomavailability',
            name='max_quantity',
            field=models.IntegerField(default=1, help_text='Maximum number of rooms of this type for the period', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
