# Generated by Django 5.2.3 on 2025-07-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_flights_capacity_roomavailability_max_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suppliers",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
