# Generated by Django 5.2.3 on 2025-07-02 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_flights_capacity_roomavailability_max_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['country', 'state', 'city', 'name']},
        ),
        migrations.AddField(
            model_name='location',
            name='code',
            field=models.CharField(blank=True, default='', help_text='IATA/ICAO code or custom code', max_length=16),
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default=1, help_text='Display name (city, airport, etc.)', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent location (for hierarchy, e.g., city belongs to country)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('country', 'Country'), ('state', 'State/Province'), ('city', 'City'), ('district', 'District/Locality'), ('airport', 'Airport'), ('terminal', 'Terminal'), ('other', 'Other')], default='city', help_text='Type of location (city, airport, terminal, etc.)', max_length=16),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['country', 'state', 'city', 'type'], name='products_lo_country_c84dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='products_lo_name_2b03d9_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['code'], name='products_lo_code_e853b5_idx'),
        ),
    ]
